### ISSUE TITLE
No internet or link

### ISSUE THREAD

**Issue by JS7803** [Killerpac/Kayuri#107]
How long will it take before to fix that? Everyone can you recommend me an app like kayuri or anything that can i watch anime

**Comment by Killerpac** [comment]
The app si working fine just tap retry if it doesn't work try re-installing the app

**Comment by JS7803** [comment]
> The app is working fine just tap retry if it doesn't work try re-installing the app

Why i cant watch anime, that release date year 2014? I cant watch world trigger always pop up no internet or no link, but the recent anime was able to play
