### ISSUE TITLE
App is not working

### ISSUE THREAD

**Issue by Dvixe** [Killerpac/Kayuri#119]
No anime is playing

**Comment by BlackoftheDawn** [comment]
My app is working when using mobile data however I cant use it on an open network like that of a library(maybe its restricted) I will try a Starbucks and let you know. Next is that I can't play the new episode of platinum end. Will also check and see if any other anime isn't working as well. Thanks and keep up the good work.

**Comment by BlackoftheDawn** [comment]
I dont know if this will help but my device is a Galaxy 8s+ for reference.

**Comment by Killerpac** [comment]
fixed you may close now
