### ISSUE TITLE
Hello from Anime X Stream Developer

### ISSUE THREAD

**Issue by mukul500** [Killerpac/Kayuri#132]
Hey, buddy nice fork Really impressed. I just want to have a little chat with you. Where we should connect?

**Comment by Killerpac** [comment]
Hey man hope you doing well

You can contact me at discord.Dropping my username and tag below

Astrix#9566

**Comment by mukul500** [comment]
Sent by name of xBlacky

**Comment by Killerpac** [comment]
Got it send a text so closing
