### ISSUE TITLE
Server error problem

### ISSUE THREAD

**Issue by Leurie02** [Killerpac/Kayuri#136]
Server error start since this day... Please help... Thanks...
![Screenshot_2022-05-06-19-55-37-42_0fe048591332d0c2eaceaca804083d38](https://user-images.githubusercontent.com/58014544/167126806-194f9d4d-f6dc-4368-b1d3-fe4ddd1ec36f.jpg)

**Comment by Killerpac** [comment]
Cannot Reproduce

**Comment by STARGAMERMJ** [comment]
> Server error start since this day... Please help... Thanks... ![Screenshot_2022-05-06-19-55-37-42_0fe048591332d0c2eaceaca804083d38](https://user-images.githubusercontent.com/58014544/167126806-194f9d4d-f6dc-4368-b1d3-fe4ddd1ec36f.jpg)

Use this app:- https://github.com/ScriptHelper/AversHenni

**Comment by ShavonHastings** [comment]
Anyone noticed that some of the animes are off-centered? Or is it just me?

**Comment by Killerpac** [comment]
> Anyone noticed that some of the animes are off-centered? Or is it just me?

name of the anime and episode no
