### ISSUE TITLE
so kayuri si consuming a lot of battery 

### ISSUE THREAD

**Issue by yui0019** [Killerpac/Kayuri#14]

**Comment by eIiminated** [comment]
could you provide more info relating to your device?

**Comment by yui0019** [comment]
so my phone brand si Huawei and I have this app calledavast cleanup and it's says battery impact 22%-------- Original Message --------Subject: Re: [Killerpac/Kayuri] so kayuri si consuming a lot of battery  (Issue #14)From: eIiminated To: Killerpac/Kayuri CC: yui0019 ,Author 
could you provide more info relating to your device?

**Comment by eIiminated** [comment]
> so my phone brand si Huawei and I have this app calledavast cleanup and it's says battery impact 22%-------- Original Message --------Subject: Re: [Killerpac/Kayuri] so kayuri si consuming a lot of battery  (Issue #14)From: eIiminated To: Killerpac/Kayuri CC: yui0019 ,Author 
> could you provide more info relating to your device?
> 
> —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

could you go into Settings > Battery and tell me what it says about the app? I'm not a fan of third-party health apps.

**Comment by yui0019** [comment]
can u see the picture that I sent youSent from my Huawei Mobile-------- Original Message --------Subject: Re: [Killerpac/Kayuri] so kayuri si consuming a lot of battery  (Issue #14)From: eIiminated To: Killerpac/Kayuri CC: yui0019 ,Author 



so my phone brand si Huawei and I have this app calledavast cleanup and it's says battery impact 22%-------- Original Message --------Subject: Re: [Killerpac/Kayuri] so kayuri si consuming a lot of battery  (Issue #14)From: eIiminated To: Killerpac/Kayuri CC: yui0019 ,Author

could you provide more info relating to your device?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.



could you go into Settings > Battery and tell me what it says about the app? I'm not a fan of third-party health apps.

**Comment by ElezeoraDraconius** [comment]
Do not use avast cleanup!  That's the one that  actually consume battery the most
