### ISSUE TITLE
backing out of any anime that I look up crashes the app

### ISSUE THREAD

**Issue by eIiminated** [Killerpac/Kayuri#15]
if I select the anime through the main menu and back out, it won't crash,
but if I look it up, select it and back out, the app crashes.

Galaxy S21 / Android 12 / One UI 4.0
Kayuri v1.2 universal release

**Comment by Killerpac** [comment]
Try the new update and see if it crashes

**Comment by eIiminated** [comment]
> Try the new update and see if it crashes
> I don't have an android 12 device to test it physically but it should work now

issue fixed.
