### ISSUE TITLE
Cant watch anime

### ISSUE THREAD

**Issue by Zking1747** [Killerpac/Kayuri#159]
![Screenshot_20220801-232838_Kayuri](https://user-images.githubusercontent.com/110410331/182185012-e9696648-90db-49ca-9a5b-64df83eda070.jpg)

Hey devs, i cant watch anime because of this bugs because they wont show the ep and anime details. I also tried with my other device but it wont show anything

**Comment by BigBoyBarney** [comment]
It works for me. Try enabling DNS over Https in the settings, maybe something's blocking it

**Comment by Rohan-511** [comment]
Try a vpn maybe it's an ISP issue

**Comment by GABIlopez** [comment]
![Screenshot_20220804-233648_Kayuri.jpg](https://user-images.githubusercontent.com/32043783/182990429-143b3f24-8196-4423-982c-fe67633b5bd2.jpg)

**Comment by Killerpac** [comment]
try reinstalling the app
