### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by Micoraheal7u** [Killerpac/Kayuri#176]
i can't watch so many anime and which i can watch few bugs like server  pop up
![Screenshot_2022-10-01-23-14-46-164_net sanic Kayuri](https://user-images.githubusercontent.com/96631108/193421733-0aa4e598-1df7-4935-8aed-79d1f2fc5239.jpg)
please do something

**Comment by Killerpac** [comment]
fix will come by tomorrow night

**Comment by Micoraheal7u** [comment]
that's great thank you ☺️

**Comment by Killerpac** [comment]
fixed in update you may close the issue

**Comment by Micoraheal7u** [comment]
thank you
