### ISSUE TITLE
Can't play any video. 

### ISSUE THREAD

**Issue by Xerx81** [Killerpac/Kayuri#18]
![Screenshot_2021-12-27-15-31-01-07_0fe048591332d0c2eaceaca804083d38](https://user-images.githubusercontent.com/91129128/147460588-21e25a22-add5-4d6a-b512-439286786ef7.png)

Just showing this in every video I play.

**Comment by Killerpac** [comment]
Enable gogo-cdn from settings as a temporary fix

**Comment by Xerx81** [comment]
> 

Tried that but it just keep loading and video never plays

**Comment by Killerpac** [comment]
The new update fixes the issues
