### ISSUE TITLE
Some anime not working and also videos quality at 360p not available

### ISSUE THREAD

**Issue by Dvixe** [Killerpac/Kayuri#24]
When i tried to play anime some of them working good but at high resolution at low quality resolution not available .And most importantly Some other anime nit loading it shows:-
![Screenshot_2022-01-07-14-17-25-425_net sanic Kayuri](https://user-images.githubusercontent.com/86739712/148518007-ccdea854-6b28-484b-afd1-68d8a2570bff.jpg)

**Comment by Killerpac** [comment]
Try backup servers for multiple links and gogoanime is making random changes in their website that's why many things are breaking 

I will try to fix it as much as possible

**Comment by Dvixe** [comment]
> Try backup servers for multiple links and gogoanime is making random changes in their website that's why many things are breaking
> 
> I will try to fix it as much as possible

Thanks a bunch
