### ISSUE TITLE
Skip Intro(Skip 85 Seconds)  option on video player

### ISSUE THREAD

**Issue by Dmnboruto** [Killerpac/Kayuri#26]
This could really help out as most people skip intros so then they only have to tap that button instead of skipping by yourself which is normally inaccurate so pls I don't know if it is easy to do so but would be much appreciated 😀

**Comment by kl3jvi** [comment]
try my app @Dmnboruto https://github.com/kl3jvi/animity

**Comment by Killerpac** [comment]
Please Refrain from Any Promotion In Issue Section @kl3jvi

**Comment by Killerpac** [comment]
@Dmnboruto I understant Your Opinion But Diffrernt Anime Have Different Anime Intro Lengths To skip so Without a Public Database To fetch the length It will be misleanding as it may skip more or less than the intro.

Most Anime Have 85-90 secs intro but some older anime have more or less

**Comment by Dmnboruto** [comment]
Then you could.d have option in setting to toggle the how much it skips.
