### ISSUE TITLE
So the video player of kayuri stopped working

### ISSUE THREAD

**Issue by Exio233** [Killerpac/Kayuri#29]
So when I was using kayuri the video player didn't load anime and now its shows 'no internet' even I have internet.

**Comment by Killerpac** [comment]
Its Working

**Comment by macguffin11** [comment]
> So when I was using kayuri the video player didn't load anime and now its shows 'no internet' even I have internet.

same with me

**Comment by macguffin11** [comment]
![Screenshot_20220125-102006_Kayuri](https://user-images.githubusercontent.com/24616430/150904965-41cfbdd9-1cc7-4b7b-bf31-954de5e097a7.png)
![Screenshot_20220125-102045_Kayuri](https://user-images.githubusercontent.com/24616430/150904969-9d311d01-5e04-45e5-b034-8f18d26de4a3.png)
Some anime like this

**Comment by AnixNyk** [comment]
Turn off back up servers in settings
