### ISSUE TITLE
Stretch button

### ISSUE THREAD

**Issue by ZeoGOD4** [Killerpac/Kayuri#3]
Can you add a stretch button in the video player? The current button crops the video and i cant read the subs
![Screenshot_2021-09-15-02-12-35-267_net sanic Kayuri](https://user-images.githubusercontent.com/76849057/133330963-02b61fa7-fe4a-4482-9639-a92becb97ce0.jpg)

**Comment by Killerpac** [comment]
Will see this

**Comment by Killerpac** [comment]
Added in the new Release
