### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Zeroo097** [Killerpac/Kayuri#30]
Can You Please Add A Progess Bar or a tab to see the how much the file is downloaded and an option to bulk download episode it's irritating to download episode one by one.BTW The app is very good.Kudos

**Comment by Zeroo097** [comment]
I Can't See Any Progess Bar in Notification

**Comment by Killerpac** [comment]
Drop Your Android Version I will Look Into It

**Comment by Zeroo097** [comment]
My Android Version is 11 and Oxygen OS 11.1.2.2

**Comment by Zeroo097** [comment]
It Seems the problem is with a few animes like aot final season part 2 but when i download a another non famous anime it shows the progress bar

**Comment by Killerpac** [comment]
Android 11 is Having Some Problems With the Notification Of The Download Will Try To Fix In Later Updates
