### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Antibodyarmy** [Killerpac/Kayuri#34]
I'm using this app with blue stacks, and when playing a video it will default to the lowest available quality. it would be nice if in the settings you could select a preferred playback quality in a drop down (360, 480, 720,1080 etc.). 

also if its possible to pull alternate titles for things from myanimelist or something like that then having a section before description that lists alternate titles. that is super helpful since sites/lists use different cover art and some light novel/manhua/manhwa adaptations have similar names/cover arts or several names and cover arts that can lead to confusion. a good example of this in practice is on KAA in the "Other Names:" section

**Comment by Killerpac** [comment]
Preffered quality is planned in the next update whereas,

Alternate titles and app ui chages will be done later
