### ISSUE TITLE
Add new website

### ISSUE THREAD

**Issue by AnixNyk** [Killerpac/Kayuri#40]
Can you please add more websites like zoro.to or tenshi.moe and add an option in the settings to change the site we want to watch from like when we will open settings it will be by default gogoanime but we can change it to zoro.to and than we can watch from that website. Please try it.

**Comment by kyoyacchi** [comment]
I think you can use _Aniyome_ for that... it has extensions of both.

**Comment by Killerpac** [comment]
Could Add But Why!!! GogoAnime Is working Perfectly Fine And I don't Want The App More Complicated Just Keep It Simple
Most Of the Websites Fetch Content From GogoAnime So I Dont Think There Is No Reason To Add Other Sources.

There Is Already A Backup Server Which Works So I Think I will Stick To GogoAnime For Now Is Situation Changes Then I will Add Other Sources
