### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by some1onLSD** [Killerpac/Kayuri#41]
Hi, I was going to watch this anime "Kabukichou Sherlock 2019" the undub version but the servers seems not working, sometime I get a picture of a database saying "server error" and sometimes it just a black screen anyway it isn't working

![Screenshot_20220204-174353_Kayuri](https://user-images.githubusercontent.com/74503778/152568132-ab026a3c-c81a-4ced-aa75-747c9e3ff192.png)
![Screenshot_20220204-173741_Kayuri](https://user-images.githubusercontent.com/74503778/152567291-cca3adf0-56c9-41d5-9319-ca540f23ee5c.png)

**Comment by Killerpac** [comment]
It Works Close and App and Try to Reopen the App
![88](https://user-images.githubusercontent.com/45239423/152576103-19971b65-a3f6-4f1e-8233-a7a60ffb7eba.PNG)

**Comment by some1onLSD** [comment]
it was weird it didn't work at all tried to clear cache and the problem persisted but it was fixed when I used a vpn and tried again, now works like a charm even without the vpn. I don't know where was the problem.
