### ISSUE TITLE
Use external downloader app

### ISSUE THREAD

**Issue by some1onLSD** [Killerpac/Kayuri#42]
Hi, 
I was thinking if it is possible to add 3rd party downloader apps like ADM or 1DM as they provide faster downloading speeds. Thanks for this app

**Comment by Killerpac** [comment]
The Download Link Requires Certain Parameters to Make it Anime Download Which External Apps Lacks!

That's Why not possible For Now But in Future Lets see I will try

**Comment by some1onLSD** [comment]
Then can you just replace the native downloader with a download manager like navi [https://github.com/TachibanaGeneralLaboratories/download-navi] maybe you could use the source code and embedded it in the app?
