### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by 13thamayun** [Killerpac/Kayuri#5]
When clicking the back button on the app to go on the homepage the app crashes for some reason
![Screenshot_20210915-202735_One UI Home](https://user-images.githubusercontent.com/90797582/133497827-5168c04f-16e8-488e-851f-401484ed00e3.jpg)

**Comment by Killerpac** [comment]
Weird it didn't crashed for any other people what's you device specs

**Comment by 13thamayun** [comment]
Samsung galaxy note 10 plus 5g 12gb ram 512gb storage

**Comment by Killerpac** [comment]
I tested it on a oneui device also but didn't crashed there try reinstalling

**Comment by 13thamayun** [comment]
Trying an arm7 version of the app, what version would be best for my phone

**Comment by 13thamayun** [comment]
![Screenshot_20210916-035623_Chrome](https://user-images.githubusercontent.com/90797582/133542011-f37f2a46-6d93-485e-95c8-a5c6d2eaf335.jpg)
Which version would you recommend

**Comment by Killerpac** [comment]
Use the universal one if you don't know your architecture

**Comment by 13thamayun** [comment]
Kindly have a look at this screen recording and it should be clear on what is happening 
https://file.io/rcXyLYHzsJPc

**Comment by 13thamayun** [comment]
> Use the universal one if you don't know your architecture

I found out my supported version its arm64

**Comment by Killerpac** [comment]
Can you try the new update see if it fixed your issue
