### ISSUE TITLE
is there a way for me to change the icon 

### ISSUE THREAD

**Issue by LPZO** [Killerpac/Kayuri#62]
Hi sorry for this question but is there a way I can change the icon of the app so i can hide it on my phone?
I really enjoy the app but my son keeps getting into it.
I just want to change the icon on my phone and maybe the name so he stops trying to go on it.

Thanks
Lucy Lue

**Comment by Dmnboruto** [comment]
You can't but you can hide it if you are on samsung

**Comment by Dmnboruto** [comment]
https://youtu.be/_vDBPEPnGxY

**Comment by Dmnboruto** [comment]
Watch that tutorial it's a Samsung feature to hide apps

**Comment by elvistony** [comment]
You could try using an app lock, it's pretty easily found in the Play Store.
