### ISSUE TITLE
App is working great but only available in 1080p

### ISSUE THREAD

**Issue by Dvixe** [Killerpac/Kayuri#67]
Please make it work on low resolution

**Comment by ShavonHastings** [comment]
Figured out the problem after some quick thinking nd have a temp fix, the video quality is locked to the quality that was set in the preferred video quality in the settings. Change that nd u should be good to go till there's an update

**Comment by Killerpac** [comment]
> Figured out the problem after some quick thinking nd have a temp fix, the video quality is locked to the quality that was set in the preferred video quality in the settings. Change that nd u should be good to go till there's an update

noice Figuring It out now i can sleep lol
