### ISSUE TITLE
I think the source code of v1.5.7 is not updated

### ISSUE THREAD

**Issue by NSomith** [Killerpac/Kayuri#69]
I downloaded the source code of v1.5.7 and ran it on my android studio after that when  I checked the version of the app it was v1.2.0 pls share the latest version

**Comment by NSomith** [comment]
The source code mentioned in the latest version does not have features like downloading? pls share the source code I am learning some new things with the help of this project.

**Comment by Killerpac** [comment]
The develop branch has the src updated

**Comment by NSomith** [comment]
Thank you so much

**Comment by NSomith** [comment]
I checked the develop branch but when I run the app it gave me a pop-up message to download the latest version 1.5.7 and also the app crashes when playing the video.

**Comment by GABIlopez** [comment]
App

**Comment by GABIlopez** [comment]
App 1.5.7

**Comment by Killerpac** [comment]
The Latest Commit Fixes the problems

**Comment by NSomith** [comment]
Thank you so much

**Comment by GABIlopez** [comment]
16.0
