### ISSUE TITLE
Does the app had restricted access from certain IPs? 

### ISSUE THREAD

**Issue by TaroMisaki98** [Killerpac/Kayuri#71]
I used to be able to open viewer without any issues with ver 1.5.7
But recently not only it only shows "No Internet or Links not found" , it had no issues when I used a VPN instead
But I had no issue when going to the source website so nost probably it's an app issue

**Comment by NSomith** [comment]
can u pls share the source code for v1.5.7 ? becz the source code that is provided does not have the latest version like downloading features

**Comment by TaroMisaki98** [comment]
Isn't the latest version 1.5.7?
You could just find it there

**Comment by NSomith** [comment]
Yes I downloaded the source code of v1.5.7 but it does not have the latest features that the build apk has also I check the develop branch but in there I got a pop-up message to download the latest version and also the app crashes when I play the video.

**Comment by TaroMisaki98** [comment]
Ok so I tried on my other phone and apparently it's not IP problem but rather
The app suddenly don't work on Huawei phones anymore (or at least my current phone, Huawei Mate10) 
I've tried phone restart, reinstalling, cache clear and nothing works

**Comment by Killerpac** [comment]
check now

**Comment by TaroMisaki98** [comment]
No, it still only work when I turn on VPNs
Else it still show the same error message "No Internet or Links Not Found"

**Comment by TaroMisaki98** [comment]
I tried with my other phone and no issue with there
So maybe there's something to do with the app itself and Huawei phones?

**Comment by Killerpac** [comment]
have u updated?
if yes then ur isp is blocking some servers

**Comment by TaroMisaki98** [comment]
Yes I've updated
After verifying with a friend of mine, there's indeed a chance that it is ISP issue
But iirc this app based it's code from AnimeXStream, which source their link domain from GogoAnime right?
If that's also the case with this app then it's strange cuz I can watch anime in Gogoanime with no issues (abeit the amount of popup ads they added)
