### ISSUE TITLE
Connection Broken

### ISSUE THREAD

**Issue by Domokaru** [Killerpac/Kayuri#72]
Looks like server destination may have changed again. App no longer working to retrieve anime.

**Comment by GABIlopez** [comment]
App

**Comment by Killerpac** [comment]
Yes!!The Sharks Took A Bite of the cables But i think now now wires are installed

**Comment by Domokaru** [comment]
Thanks @Killerpac , is there somewhere we can donate to you?

**Comment by GABIlopez** [comment]
Anime 
https://myanimelist.net/
