### ISSUE TITLE
App crashes and not playing/downloading anime

### ISSUE THREAD

**Issue by The-BOT-says** [Killerpac/Kayuri#73]
App sudden crushes when I try to download any anime episode, and also episodes of any anime series is not loading....

Fix this ASAP it sucks

**Comment by 3008dead** [comment]
@Killerpac after the new update again some problem has occurred. Please see to it

**Comment by GABIlopez** [comment]
App

**Comment by Killerpac** [comment]
Why Bully me

**Comment by issamaf80** [comment]
> Why Bully me new update will come I already have the solution

Thank you for supporting the app it it would be great if you could change from gogoanime scrape to a new one?

**Comment by Killerpac** [comment]
> > Why Bully me new update will come I already have the solution
> 
> Thank you for supporting the app it a lasting solution would be if you could change from gogoanime scrape to a new one?

GogoAnime Has Faster Servers than all Other Websites And Majority Fetch Content From Gogo 
Zoro Is There But someetimes its slow especially for old anime and gogoanime updates content faster than most of the sites

**Comment by issamaf80** [comment]
> GogoAnime Has Faster Servers than all Other Websites And Majority Fetch Content From Gogo Zoro Is There But someetimes its slow especially for old anime and gogoanime updates content faster than most of the sites

I see thanks for letting me know and thanks again for fixing the app

**Comment by issamaf80** [comment]
> > > Why Bully me new update will come I already have the solution
> > 
> > 
> > Thank you for supporting the app it a lasting solution would be if you could change from gogoanime scrape to a new one?
> 
> GogoAnime Has Faster Servers than all Other Websites And Majority Fetch Content From Gogo Zoro Is There But someetimes its slow especially for old anime and gogoanime updates content faster than most of the sites

I heard that GoGoAnime scraps their Videos from streamani.net what do you think?

**Comment by Killerpac** [comment]
gogoanime, streamani , gogoplay all are same thing operated by one entity

**Comment by GABIlopez** [comment]
![Screenshot_20220702-222832_Kayuri.jpg](https://user-images.githubusercontent.com/32043783/177020938-f818be28-c232-42b9-aacd-3ae8dd9f0aad.jpg)

**Comment by GABIlopez** [comment]
Kayuri anime 
144p 240p 360p 480p 720p60 1080p60
