### ISSUE TITLE
Something like bug 

### ISSUE THREAD

**Issue by 3008dead** [Killerpac/Kayuri#76]
@Killerpac  after update also something like this is happening ....

![Screenshot_2022-03-04-23-43-23-26_0fe048591332d0c2eaceaca804083d38](https://user-images.githubusercontent.com/77578650/156819093-264b7882-2ce9-456a-b5f9-19fa8c090daa.jpg)

**Comment by Killerpac** [comment]
Cannot reproduce please give the anime name with ep no and Android version

**Comment by 3008dead** [comment]
> Cannot reproduce please give the anime name with ep no and Android version

Anime name attack on titan last season 
Episode 1 and Android 11

**Comment by 3008dead** [comment]
> Cannot reproduce please give the anime name with ep no and Android version

Not only aot but its for

**Comment by Killerpac** [comment]
first try a vpn if not works then try reinstalling the app

**Comment by 3008dead** [comment]
> first try a vpn if not works then try reinstalling the app

Started working after reinstalling the app ..... 

Thank for your work 🙇🙇🙇
