### ISSUE TITLE
New issue kayuri not working please fix it

### ISSUE THREAD

**Issue by Dvixe** [Killerpac/Kayuri#9]
No anime plays please fix it ..it is the best anime app i have ever use please fix the issue

**Comment by Killerpac** [comment]
It's working I don't see any errors

**Comment by Dvixe** [comment]
![Screenshot_2021-11-07-13-14-41-880_net sanic Kayuri](https://user-images.githubusercontent.com/86739712/140636889-aee4fe4e-d00f-45ce-8368-01a6c5ab2456.jpg)

**Comment by Dvixe** [comment]
It shows this ever time

**Comment by Killerpac** [comment]
Yes just saw it fix will come please wait

**Comment by Killerpac** [comment]
uninstall the previous version nd install the new version
