### ISSUE TITLE
Can't increase playback speed to 4x like other anime streaming website.

### ISSUE THREAD

**Issue by ghost** [Killerpac/Kayuri#92]
Can't increase playback speed to 4x like other anime streaming website.Can't select Default playback speed.Make the app more privacy friendly

**Comment by Killerpac** [comment]
2x speed is there in player which i think is enough 4x is too much lol 
and about privacy the app is open source and has no trackers 
I dont know what else privacy features you want

**Comment by JustaUser0** [comment]
> 2x speed is there in player which i think is enough 4x is too much lol and about privacy the app is open source and has no trackers I dont know what else privacy features you want

Other sites Support 3x speed. Please add this option in this video player
