### ISSUE TITLE
For some anime it shows error

### ISSUE THREAD

**Issue by AnixNyk** [Killerpac/Kayuri#93]
![Screenshot_2022-03-26-14-19-06-199_net sanic Kayuri](https://user-images.githubusercontent.com/92598688/160232208-3f64cb20-34db-4f72-bf8c-aa33adc02d75.jpg)
For some anime it shows this error not for all anime. Some anime r playing normally and some r showing this. Please help

**Comment by Killerpac** [comment]
Isp's are blocking some urls that's why it shows error
