### ISSUE TITLE
Feature Request: If an anime has more than 1 season have it be in one page with the ability to select (example video attached)

### ISSUE THREAD

**Issue by issamaf80** [Killerpac/Kayuri#96]
Hello thanks again for the great app I would like to see this feature as it will keep the app far more organized for example iruma-kun has more than 1 season instead of every time looking for a new season have it be in one page with the ability to select .

![20220327150312 (1)](https://user-images.githubusercontent.com/67523843/160289976-f97f5454-2557-4986-bdc8-6983ba69005d.gif)

**Comment by Dvixe** [comment]
Which app is this

**Comment by issamaf80** [comment]
> Which app is this

Kamyroll its not available anymore
