### ISSUE TITLE
Sort of server down

### ISSUE THREAD

**Issue by LordOfDawns** [Killerpac/Kayuri#97]
Sort of server down maybe..... All old eps are buffering but not the new episodes (airing ones)...... Take ousama ranking(dub version) for an example, till 
ep 17th in 1080p is buffering (only running in 100kb/s) but if i tap on the  18th episode it straightly goes 1mb/s and doesn't buffers at all........ Like this old eps of every anime is buffering. Dev please fix this

**Comment by Killerpac** [comment]
yes noticed it apparently gogoanime is using some shady sites to store their content as a result isp's are blocking it but i found a way to bypass it. It will be fixed by next update

**Comment by Killerpac** [comment]
issue fixed closing
