### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by vikd-94** [Killerpac/Kayuri#98]
Not able to play any videos. App keeps crashing when trying to play anything.

**Comment by 11Nitz** [comment]
same issue with me

**Comment by CloudZero1** [comment]
Same issue

**Comment by razwatsup** [comment]
Was refered to here by xtream topıc, nothing plays

**Comment by Killerpac** [comment]
Working  On Fixing The App Don't Worry Guys

**Comment by vikd-94** [comment]
> Working On Fixing The App Don't Worry Guys

Thanks for the quick update, app is working again!
